import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin } from "react-icons/ai";
import { AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import profile_picture from '../public/IMG_6620.jpg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>João Bota Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-zinc-800 px-40">
        <section className=" bg-zinc-800  min-h-screen">
          <nav className="py-8 mb-12 flex justify-between">
            <h1 className=" text-xl font-Varela text-white">Portfolio</h1>
            <ul className="flex items-center">
              <div className="text-3xl flex justify-center gap-2 text-white"> <li>
                <AiFillLinkedin />
              </li>
                <li><AiFillGithub />
                </li>
                </div>
              <li>
                <a
                  className=" bg-gradient-to-r from-orange-500 to-pink-600 text-white px-4 py-1  rounded-xl ml-6" href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <section>
            <div className=" relative mx-auto w-72"><Image className="rounded-full shadow-sm" src={profile_picture} /></div>
            <div className="p-8">
              <h2 className="text-transparent text-6xl bg-clip-text bg-gradient-to-r from-orange-500 to-pink-600">João Bota</h2>
              <h3 className="text-2xl py-2 font-Varela text-transparent bg-clip-text bg-gradient-to-r from-white to-zinc-600">Developer</h3>
              <p className="text-md py-3 leading-8 font-Varela text-white">
                Software Engineer capable of developing efficient scalable
                full-stack web-based applications, along with critical and problem-solving
                skills for design and construction of software and work
                collaboratively on software development.
              </p>
            </div>
          </section>

          <section>
            <div className=" text-white p-10">
              <h3 className="text-5xl text-transparent bg-clip-text bg-gradient-to-r from-slate-50 to-zinc-600 py-4 ">Projects</h3>
              <p >Since the beggining of my journey as a <span className=" text-transparent bg-clip-text bg-gradient-to-r from-orange-500 to-pink-600">Software Engineer</span>, I've done many projects both for business and consumer use.</p>
            </div>
            <div className="lg:flex shadow-lg shadow-black p-10 rounded-xl">
              <p className="text-white">
              dakpoawciodaipcduja
              w8mdcua80umdc8auedmc0awd98
              acmwu0d9cuaw09u0890cmq30ud
              0c90w9ac9cdw</p>
            </div>
          </section>

        </section>
      </main>
    </div>
  );
}
